import React from "react";
import { Link } from "react-router-dom";
import StarRateSection from "../StarRateSection";
import {
  Avatar,
  CommentAuthorName,
  CommentAvatar,
  CommentContent,
  CommentList,
  CommentMain,
  CommentMedia,
  CommentMediaContainer,
  CommentProduct,
  CommentTime,
  CommentWrap,
  IMGAvatar,
  Media,
  MediaContent,
  MediaPlaceholder,
  MediaWrap,
  OrderVariation,
  OverviewFilter,
  PaginationList,
  PersonalRating,
  Placeholder,
  ProductReviewContainer,
  ProductReviewWrap,
  RatingBriefing,
  RatingFilters,
  RatingOutOf,
  RatingReviewStar,
  RatingScore,
  RatingScoreWrap,
  ReviewHeader,
  ReviewList,
  ReviewOverview,
} from "./ProductReview.elements";

const ProductReview = () => {
  return (
    <ProductReviewWrap>
      <ProductReviewContainer>
        <ReviewHeader>ĐÁNH GIÁ SẢN PHẨM</ReviewHeader>
        <ReviewOverview>
          <RatingBriefing>
            <RatingScoreWrap>
              <RatingScore>4.8</RatingScore>
              <RatingOutOf> out of 5</RatingOutOf>
            </RatingScoreWrap>
            <RatingReviewStar>
              <StarRateSection />
            </RatingReviewStar>
          </RatingBriefing>
          <RatingFilters>
            <OverviewFilter>Tất cả</OverviewFilter>
            <OverviewFilter>5 Sao (1,2k)</OverviewFilter>
            <OverviewFilter>4 Sao (48)</OverviewFilter>
            <OverviewFilter>3 Sao (30)</OverviewFilter>
            <OverviewFilter>2 Sao (1,2k)</OverviewFilter>
            <OverviewFilter>1 Sao (1,2k)</OverviewFilter>
            <OverviewFilter>Có Bình luận (496)</OverviewFilter>
            <OverviewFilter>Có hình ảnh / video (397)</OverviewFilter>
          </RatingFilters>
        </ReviewOverview>
        <ReviewList>
          <CommentList>
            <CommentProduct>
              <CommentWrap>
                <CommentAvatar>
                  <Avatar>
                    <Placeholder>
                      <svg
                        enableBackground="new 0 0 15 15"
                        viewBox="0 0 15 15"
                        x="0"
                        y="0"
                      >
                        <g>
                          <circle
                            cx="7.5"
                            cy="4.5"
                            fill="none"
                            r="3.8"
                            strokeMiterlimit="10"
                          ></circle>
                          <path
                            d="m1.5 14.2c0-3.3 2.7-6 6-6s6 2.7 6 6"
                            fill="none"
                            strokeLinecap="round"
                            strokeMiterlimit="10"
                          ></path>
                        </g>
                      </svg>
                    </Placeholder>
                    <IMGAvatar src="https://cf.shopee.vn/file/b4ac3f0575b2e11cfa528439f6abcfbb_tn"></IMGAvatar>
                  </Avatar>
                </CommentAvatar>
                <CommentMain>
                  <CommentAuthorName>yumez</CommentAuthorName>
                  <PersonalRating>
                    <StarRateSection />
                  </PersonalRating>
                  <OrderVariation>
                    Phân loại hàng: VN.N95 4 lớp (10cái)
                  </OrderVariation>
                  <CommentContent>
                    Do dịch bệnh nên tgian giao hàng khá lâu. Sản phẩm cũng tạm
                    đc. Tuy nhiên mình thấy hình ảnh của shop đăng và sản phẩm
                    nhận được bên ngoài có vẻ khác nhau. Nên không biết là có
                    đúng hàng chuẩn không. Hy vọng đc nghe giải thích. Và nếu
                    hàng bên mình chuẩnthì shop hãy để ảnh thật đi ạ. Tránh hiểu
                    lầm
                  </CommentContent>
                  <CommentMedia>
                    <CommentMediaContainer>
                      <Media>
                        <MediaWrap>
                          <MediaPlaceholder>
                            <svg
                              enableBackground="new 0 0 15 15"
                              viewBox="0 0 15 15"
                              x="0"
                              y="0"
                            >
                              <g>
                                <rect
                                  fill="none"
                                  height="8"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  width="10"
                                  x="1"
                                  y="4.5"
                                ></rect>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="1"
                                  x2="11"
                                  y1="6.5"
                                  y2="6.5"
                                ></line>
                                <rect
                                  fill="none"
                                  height="3"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  width="3"
                                  x="11"
                                  y="6.5"
                                ></rect>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="1"
                                  x2="11"
                                  y1="14.5"
                                  y2="14.5"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="6"
                                  x2="6"
                                  y1=".5"
                                  y2="3"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="3.5"
                                  x2="3.5"
                                  y1="1"
                                  y2="3"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="8.5"
                                  x2="8.5"
                                  y1="1"
                                  y2="3"
                                ></line>
                              </g>
                            </svg>
                          </MediaPlaceholder>
                          <MediaContent
                            src={
                              require("../../images/Products/Special/thumb/Thumb1/1_540x.jpg")
                                .default
                            }
                          ></MediaContent>
                        </MediaWrap>
                      </Media>
                      <Media>
                        <MediaWrap>
                          <MediaPlaceholder>
                            <svg
                              enableBackground="new 0 0 15 15"
                              viewBox="0 0 15 15"
                              x="0"
                              y="0"
                            >
                              <g>
                                <rect
                                  fill="none"
                                  height="8"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  width="10"
                                  x="1"
                                  y="4.5"
                                ></rect>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="1"
                                  x2="11"
                                  y1="6.5"
                                  y2="6.5"
                                ></line>
                                <rect
                                  fill="none"
                                  height="3"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  width="3"
                                  x="11"
                                  y="6.5"
                                ></rect>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="1"
                                  x2="11"
                                  y1="14.5"
                                  y2="14.5"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="6"
                                  x2="6"
                                  y1=".5"
                                  y2="3"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="3.5"
                                  x2="3.5"
                                  y1="1"
                                  y2="3"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="8.5"
                                  x2="8.5"
                                  y1="1"
                                  y2="3"
                                ></line>
                              </g>
                            </svg>
                          </MediaPlaceholder>
                          <MediaContent
                            src={
                              require("../../images/Products/Special/thumb/Thumb1/3_540x.jpg")
                                .default
                            }
                          ></MediaContent>
                        </MediaWrap>
                      </Media>
                      <Media>
                        <MediaWrap>
                          <MediaPlaceholder>
                            <svg
                              enableBackground="new 0 0 15 15"
                              viewBox="0 0 15 15"
                              x="0"
                              y="0"
                            >
                              <g>
                                <rect
                                  fill="none"
                                  height="8"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  width="10"
                                  x="1"
                                  y="4.5"
                                ></rect>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="1"
                                  x2="11"
                                  y1="6.5"
                                  y2="6.5"
                                ></line>
                                <rect
                                  fill="none"
                                  height="3"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  width="3"
                                  x="11"
                                  y="6.5"
                                ></rect>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="1"
                                  x2="11"
                                  y1="14.5"
                                  y2="14.5"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="6"
                                  x2="6"
                                  y1=".5"
                                  y2="3"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="3.5"
                                  x2="3.5"
                                  y1="1"
                                  y2="3"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="8.5"
                                  x2="8.5"
                                  y1="1"
                                  y2="3"
                                ></line>
                              </g>
                            </svg>
                          </MediaPlaceholder>
                          <MediaContent
                            src={
                              require("../../images/Products/Special/thumb/Thumb1/1_540x.jpg")
                                .default
                            }
                          ></MediaContent>
                        </MediaWrap>
                      </Media>
                      <Media>
                        <MediaWrap>
                          <MediaPlaceholder>
                            <svg
                              enableBackground="new 0 0 15 15"
                              viewBox="0 0 15 15"
                              x="0"
                              y="0"
                            >
                              <g>
                                <rect
                                  fill="none"
                                  height="8"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  width="10"
                                  x="1"
                                  y="4.5"
                                ></rect>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="1"
                                  x2="11"
                                  y1="6.5"
                                  y2="6.5"
                                ></line>
                                <rect
                                  fill="none"
                                  height="3"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  width="3"
                                  x="11"
                                  y="6.5"
                                ></rect>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="1"
                                  x2="11"
                                  y1="14.5"
                                  y2="14.5"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="6"
                                  x2="6"
                                  y1=".5"
                                  y2="3"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="3.5"
                                  x2="3.5"
                                  y1="1"
                                  y2="3"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="8.5"
                                  x2="8.5"
                                  y1="1"
                                  y2="3"
                                ></line>
                              </g>
                            </svg>
                          </MediaPlaceholder>
                          <MediaContent
                            src={
                              require("../../images/Products/Special/thumb/Thumb1/1_540x.jpg")
                                .default
                            }
                          ></MediaContent>
                        </MediaWrap>
                      </Media>
                      <Media>
                        <MediaWrap>
                          <MediaPlaceholder>
                            <svg
                              enableBackground="new 0 0 15 15"
                              viewBox="0 0 15 15"
                              x="0"
                              y="0"
                            >
                              <g>
                                <rect
                                  fill="none"
                                  height="8"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  width="10"
                                  x="1"
                                  y="4.5"
                                ></rect>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="1"
                                  x2="11"
                                  y1="6.5"
                                  y2="6.5"
                                ></line>
                                <rect
                                  fill="none"
                                  height="3"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  width="3"
                                  x="11"
                                  y="6.5"
                                ></rect>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="1"
                                  x2="11"
                                  y1="14.5"
                                  y2="14.5"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="6"
                                  x2="6"
                                  y1=".5"
                                  y2="3"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="3.5"
                                  x2="3.5"
                                  y1="1"
                                  y2="3"
                                ></line>
                                <line
                                  fill="none"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeMiterlimit="10"
                                  x1="8.5"
                                  x2="8.5"
                                  y1="1"
                                  y2="3"
                                ></line>
                              </g>
                            </svg>
                          </MediaPlaceholder>
                          <MediaContent
                            src={
                              require("../../images/Products/Special/thumb/Thumb1/1_540x.jpg")
                                .default
                            }
                          ></MediaContent>
                        </MediaWrap>
                      </Media>
                    </CommentMediaContainer>
                  </CommentMedia>
                  <CommentTime>2021-10-23 01:30</CommentTime>
                </CommentMain>
              </CommentWrap>
            </CommentProduct>
          </CommentList>
          <PaginationList></PaginationList>
        </ReviewList>
      </ProductReviewContainer>
    </ProductReviewWrap>
  );
};

export default ProductReview;
