import React from "react";
import StarRateSection from "../StarRateSection";
import {
  Avatar,
  CommentAuthorName,
  CommentAvatar,
  CommentContent,
  CommentMain,
  CommentMedia,
  CommentMediaContainer,
  CommentTime,
  CommentWrap,
  IMGAvatar,
  Media,
  MediaContent,
  MediaPlaceholder,
  MediaWrap,
  OrderVariation,
  PersonalRating,
  Placeholder,
} from "./Comment.elements";

const Comment = ({ data }) => {
  return (
    <CommentWrap>
      <CommentAvatar>
        <Avatar>
          <Placeholder>
            <svg
              enableBackground="new 0 0 15 15"
              viewBox="0 0 15 15"
              x="0"
              y="0"
            >
              <g>
                <circle
                  cx="7.5"
                  cy="4.5"
                  fill="none"
                  r="3.8"
                  strokeMiterlimit="10"
                ></circle>
                <path
                  d="m1.5 14.2c0-3.3 2.7-6 6-6s6 2.7 6 6"
                  fill="none"
                  strokeLinecap="round"
                  strokeMiterlimit="10"
                ></path>
              </g>
            </svg>
          </Placeholder>
          <IMGAvatar
            className=" blur-up lazyload "
            src="https://cf.shopee.vn/file/b4ac3f0575b2e11cfa528439f6abcfbb_tn"
          ></IMGAvatar>
        </Avatar>
      </CommentAvatar>
      <CommentMain>
        <CommentAuthorName>{data.email}</CommentAuthorName>
        <PersonalRating>
          <StarRateSection />
        </PersonalRating>
        <OrderVariation>Phân loại hàng: VN.N95 4 lớp (10cái)</OrderVariation>
        <CommentContent>{data.body}</CommentContent>
        <CommentMedia>
          <CommentMediaContainer>
            <Media>
              <MediaWrap>
                <MediaPlaceholder>
                  <svg
                    enableBackground="new 0 0 15 15"
                    viewBox="0 0 15 15"
                    x="0"
                    y="0"
                  >
                    <g>
                      <rect
                        fill="none"
                        height="8"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        width="10"
                        x="1"
                        y="4.5"
                      ></rect>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="1"
                        x2="11"
                        y1="6.5"
                        y2="6.5"
                      ></line>
                      <rect
                        fill="none"
                        height="3"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        width="3"
                        x="11"
                        y="6.5"
                      ></rect>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="1"
                        x2="11"
                        y1="14.5"
                        y2="14.5"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="6"
                        x2="6"
                        y1=".5"
                        y2="3"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="3.5"
                        x2="3.5"
                        y1="1"
                        y2="3"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="8.5"
                        x2="8.5"
                        y1="1"
                        y2="3"
                      ></line>
                    </g>
                  </svg>
                </MediaPlaceholder>
                <MediaContent
                  src={
                    require("../../images/Products/Special/thumb/Thumb1/1_540x.jpg")
                      .default
                  }
                  className=" blur-up lazyload "
                ></MediaContent>
              </MediaWrap>
            </Media>
            <Media>
              <MediaWrap>
                <MediaPlaceholder>
                  <svg
                    enableBackground="new 0 0 15 15"
                    viewBox="0 0 15 15"
                    x="0"
                    y="0"
                  >
                    <g>
                      <rect
                        fill="none"
                        height="8"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        width="10"
                        x="1"
                        y="4.5"
                      ></rect>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="1"
                        x2="11"
                        y1="6.5"
                        y2="6.5"
                      ></line>
                      <rect
                        fill="none"
                        height="3"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        width="3"
                        x="11"
                        y="6.5"
                      ></rect>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="1"
                        x2="11"
                        y1="14.5"
                        y2="14.5"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="6"
                        x2="6"
                        y1=".5"
                        y2="3"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="3.5"
                        x2="3.5"
                        y1="1"
                        y2="3"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="8.5"
                        x2="8.5"
                        y1="1"
                        y2="3"
                      ></line>
                    </g>
                  </svg>
                </MediaPlaceholder>
                <MediaContent
                  src={
                    require("../../images/Products/Special/thumb/Thumb1/3_540x.jpg")
                      .default
                  }
                  className=" blur-up lazyload "
                ></MediaContent>
              </MediaWrap>
            </Media>
            <Media>
              <MediaWrap>
                <MediaPlaceholder>
                  <svg
                    enableBackground="new 0 0 15 15"
                    viewBox="0 0 15 15"
                    x="0"
                    y="0"
                  >
                    <g>
                      <rect
                        fill="none"
                        height="8"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        width="10"
                        x="1"
                        y="4.5"
                      ></rect>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="1"
                        x2="11"
                        y1="6.5"
                        y2="6.5"
                      ></line>
                      <rect
                        fill="none"
                        height="3"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        width="3"
                        x="11"
                        y="6.5"
                      ></rect>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="1"
                        x2="11"
                        y1="14.5"
                        y2="14.5"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="6"
                        x2="6"
                        y1=".5"
                        y2="3"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="3.5"
                        x2="3.5"
                        y1="1"
                        y2="3"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="8.5"
                        x2="8.5"
                        y1="1"
                        y2="3"
                      ></line>
                    </g>
                  </svg>
                </MediaPlaceholder>
                <MediaContent
                  src={
                    require("../../images/Products/Special/thumb/Thumb1/1_540x.jpg")
                      .default
                  }
                  className=" blur-up lazyload "
                ></MediaContent>
              </MediaWrap>
            </Media>
            <Media>
              <MediaWrap>
                <MediaPlaceholder>
                  <svg
                    enableBackground="new 0 0 15 15"
                    viewBox="0 0 15 15"
                    x="0"
                    y="0"
                  >
                    <g>
                      <rect
                        fill="none"
                        height="8"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        width="10"
                        x="1"
                        y="4.5"
                      ></rect>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="1"
                        x2="11"
                        y1="6.5"
                        y2="6.5"
                      ></line>
                      <rect
                        fill="none"
                        height="3"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        width="3"
                        x="11"
                        y="6.5"
                      ></rect>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="1"
                        x2="11"
                        y1="14.5"
                        y2="14.5"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="6"
                        x2="6"
                        y1=".5"
                        y2="3"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="3.5"
                        x2="3.5"
                        y1="1"
                        y2="3"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="8.5"
                        x2="8.5"
                        y1="1"
                        y2="3"
                      ></line>
                    </g>
                  </svg>
                </MediaPlaceholder>
                <MediaContent
                  src={
                    require("../../images/Products/Special/thumb/Thumb1/1_540x.jpg")
                      .default
                  }
                  className=" blur-up lazyload "
                ></MediaContent>
              </MediaWrap>
            </Media>
            <Media>
              <MediaWrap>
                <MediaPlaceholder>
                  <svg
                    enableBackground="new 0 0 15 15"
                    viewBox="0 0 15 15"
                    x="0"
                    y="0"
                  >
                    <g>
                      <rect
                        fill="none"
                        height="8"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        width="10"
                        x="1"
                        y="4.5"
                      ></rect>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="1"
                        x2="11"
                        y1="6.5"
                        y2="6.5"
                      ></line>
                      <rect
                        fill="none"
                        height="3"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        width="3"
                        x="11"
                        y="6.5"
                      ></rect>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="1"
                        x2="11"
                        y1="14.5"
                        y2="14.5"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="6"
                        x2="6"
                        y1=".5"
                        y2="3"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="3.5"
                        x2="3.5"
                        y1="1"
                        y2="3"
                      ></line>
                      <line
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeMiterlimit="10"
                        x1="8.5"
                        x2="8.5"
                        y1="1"
                        y2="3"
                      ></line>
                    </g>
                  </svg>
                </MediaPlaceholder>
                <MediaContent
                  src={
                    require("../../images/Products/Special/thumb/Thumb1/1_540x.jpg")
                      .default
                  }
                  className=" blur-up lazyload "
                ></MediaContent>
              </MediaWrap>
            </Media>
          </CommentMediaContainer>
        </CommentMedia>
        <CommentTime>2021-10-23 01:30</CommentTime>
      </CommentMain>
    </CommentWrap>
  );
};

export default Comment;
