const userTypes = {
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  USER_ERROR: "USER_ERROR",
  LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
};

export default userTypes;
